# Generated by Django 4.1.7 on 2023-02-28 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cnpj',
            field=models.CharField(default='00000000000000', max_length=14),
        ),
    ]
