# Generated by Django 4.1.7 on 2023-02-28 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_cliente_cnpj'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='cnpj',
            new_name='cpf_cnpj',
        ),
    ]
